# Reference: https://www.appveyor.com/docs/appveyor-yml/
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#
image: Visual Studio 2017
# version format
version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_commits:
  message: /updated readme.*

#---------------------------------#
#    environment configuration    #
#---------------------------------#
install:
  - git clone https://github.com/LeanKit-Labs/WazuhOSSecDSC.git
  - ps: Install-PackageProvider -Name -NuGet -MinimumVersion 2.8.5.201 -Force
  - ps: Install-Module -Name Pester -Repository PSGallery -Force


#---------------------------------#
#       build configuration       #
#---------------------------------#
build: off



#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
  - ps: $TestResultsFile = ".\TestResults.xml"
  - ps: $res = Invoke-Pester ".\Tests" -OutputFormat NUnitXml -OutPutFIle TestResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path TestResultsFile))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}


#---------------------------------#
#         notifications           #
#---------------------------------#
notifications:
# Slack
  - provider: Slack
    incoming_webhook:
      secure: dwwqoJvZSbvA+yNSLTrEOm4uGwHIhmSvB5H5dLZDliGWzrPeHQdrNQP24LowzszSepUIOYbi5iGp+gD+ZGK0ecZjZ0zw+G2cAIbWuwWESKA=

